version: "3"
services: 
  consul:
    image: consul
    ports:
      - 8300:8300
      - 8301:8301
      - 8301:8301/udp
      - 8302:8302
      - 8302:8302/udp
      - 8400:8400
      - 8500:8500
      - 53:53/udp
    volumes:
      - ./consul.d:/consul/consul.d
      - ./data:/consul/data
    command: consul agent -config-dir=/consul/consul.d -server -bootstrap -client=0.0.0.0 -data-dir=/consul/data
  
